name: CI
on:
  pull_request:
  # push:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install modules
        run: yarn

      - name: Run TypeScript compiler
        run: tsc

      - name: Run ESLint
        run: yarn eslint .

  build-and-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build:skip
          start: yarn start
          browser: chrome

      - name: Save Cypress artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-artifacts
          path: cypress/results/screenshots/

      - name: List screenshots
        if: failure()
        run: |
          counter=1
          screenshots=$(find cypress/results/screenshots -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.gif' \) -print0 | while IFS= read -r -d '' file; do
            new_name="${counter}.png"
            mv "$file" "$new_name"
            ((counter++))
          done)
          echo "::set-output name=screenshots::${screenshots}"
        id: list
  

      - name: Create or update comment
        if: failure()
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');
            const screenshots = '${{ steps.list.outputs.screenshots }}'.split(' ');
            let imgs = screenshots.map(name => {
              return `![${name}](https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}/files/${path.join('cypress/results/screenshots', name)})`;
            });
            const body = `## Cypress Screenshots\n\n${imgs.join('\n')}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });