name: CI
on:
  workflow_dispatch:
  pull_request:
  # push:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install modules
        run: yarn

      - name: Run TypeScript compiler
        run: tsc

      - name: Run ESLint
        run: yarn eslint .

  build-and-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build:skip
          start: yarn start
          browser: chrome
      
      - name: Find and rename screenshots
        id: list
        if: failure()
        run: |
          mkdir cypress/results/screenshots-${{ github.run_id }}
          imgs=$(find cypress/results/screenshots -type f -name '*.png' | xargs)
          renamed_imgs=($(for i in "${!imgs[@]}"; do echo "$(echo ${imgs[$i]} | sed "s/\/.*.png/\/results\/screenshots-${{ github.run_id }}\/screenshot${i+1}.png/")"; done))
          echo "Cypress Screenshots:"
          for i in "${!imgs[@]}"; do  
            mv "${imgs[$i]}" "${renamed_imgs[$i]}"; 
            echo "${imgs[$i]}  >>>   ${renamed_imgs[$i]}"; 
          done

      - name: Checkout cypress-output repository
        if: failure()
        uses: actions/checkout@v4
        with:
          repository: BuddhaNexus/cypress-output
          path: ./cypress-output

      - name: Copy Cypress media to cypress-output
        if: failure()
        run: |
          cp -r cypress/results cypress-output/
    

      - name: Add to cypress-output repository
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd cypress-output
          git config --unset-all http.https://github.com/.extraheader
          git config user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git config user.name '${{ github.actor }}'
          git add -A
          git commit -m "Add cypress media results for ${{ github.run_id }}"
          git push origin main


      - name: Create comment with screenshots
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const screenshotsDir = 'cypress/results/screenshots-${{ github.run_id }}';
            const screenshots = fs.readdirSync(screenshotsDir).filter(file => file.endsWith('.png')).map(file => {
              const filePath = path.join(screenshotsDir, file);
              const url = `https://github.com/BuddhaNexus/cypress-output/blob/main/${filePath}`;
              return `![${file}](${url}`;
            });
            const body = `## Cypress Screenshots\n\n${screenshots.join('\n')}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
