name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      
      - name: Install modules
        run: yarn
      
      - name: Run TypeScript compiler
        run: tsc
      
      - name: Run ESLint
        run: yarn eslint .

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-run:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: "18"
            cache: "yarn"

        - name: Download the build folder
          uses: actions/download-artifact@v3
          with:
            name: build
            path: build

        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            start: yarn start
            browser: chrome