name: CI
on:
  pull_request:
  # push:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install modules
        run: yarn

      - name: Run TypeScript compiler
        run: tsc

      - name: Run ESLint
        run: yarn eslint .

  build-and-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build:skip
          start: yarn start
          browser: chrome
      
      - name: Find and rename screenshots
        id: list
        if: failure()
        run: |
          mkdir cypress/results/screenshots-${{ github.head_ref }}
          imgs=$(find cypress/results/screenshots -type f -name '*.png' | xargs)
          renamed_imgs=($(for i in "${!imgs[@]}"; do echo "$(echo ${imgs[$i]} | sed "s/\/.*.png/\/results\/screenshots-${{ github.head_ref }}\/screenshot${i+1}.png/")"; done))
          echo "Cypress Screenshots:"
          for i in "${!imgs[@]}"; do  
            mv "${imgs[$i]}" "${renamed_imgs[$i]}"; 
            echo "${imgs[$i]}  >>>   ${renamed_imgs[$i]}"; 
          done

      - name: Push to cypress-testing repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure()
        run: |
          git clone https://github.com/BuddhaNexus/cypress-testing.git
          cd cypress-testing
          cp -r ../cypress/results .
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git config --unset-all http.https://github.com/.extraheader
          git add -A
          git commit -m "Add cypress media results for ${{ github.head_ref }}"
          git push origin main


      - name: Create comment with screenshots
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const screenshotsDir = 'cypress/results/screenshots-${{ github.head_ref }}';
            const screenshots = fs.readdirSync(screenshotsDir).filter(file => file.endsWith('.png')).map(file => {
              const filePath = path.join(screenshotsDir, file);
              const url = `https://github.com/BuddhaNexus/cypress-testing/blob/main/${filePath}`;
              return `![${file}](${url}`;
            });
            const body = `## Cypress Screenshots\n\n${screenshots.join('\n')}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
