name: CI
on:
  pull_request:
  push:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install modules
        run: yarn

      - name: Run TypeScript compiler
        run: tsc

      - name: Run ESLint
        run: yarn eslint .

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      # TODO: determine where tests should be run. Dev server / Docker container / other?
      - name: Start dev server
        run: yarn dev & echo $! > .pidfile

      - name: Delay
        run: sleep 60s

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Stop dev server
        run: kill $(cat .pidfile)